name: dashboard
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.10
  - sqlalchemy=1.4
  - pip
  - pip:
      - git+https://github.com/powercex/hummingbot.git@70c9070c4e86a125c962058768e5a1c3766ac68a
      - numpy==1.26.4
      - streamlit==1.33.0
      - watchdog
      - python-dotenv
      - plotly
      - pycoingecko
      - glom
      - defillama
      - statsmodels
      - pandas_ta==0.3.14b
      - pyyaml
      - pathlib
      - st_pages
      - streamlit-elements==0.1.*
      - streamlit-authenticator==0.3.2
      - pydantic==1.10.4
      - flake8
      - isort
      - pre-commit
